name: wms_udara_jadi_bersih_frontend
description: A new Flutter project for PT. Udara Jadi Bersih WMS.
version: 1.0.0+1
environment:
  sdk: ">=2.19.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  http: ^0.0.8
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^4.0.0
  flutter_qr_reader: ^0.1.0
  qr_flutter: ^4.0.0
  fl_chart: ^0.13.0
  printing: ^2.0.0
  excel: ^2.0.1
  path_provider: ^2.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true